#!/bin/sh
mkdir /judge
cd /judge || exit
curl -L https://github.com/vuthanhtrung2010/judge-server/archive/master.tar.gz | tar -xz --strip-components=1
python3 -m venv --prompt=DMOJ env
env/bin/pip3 install -e .
runuser -u judge -w PATH -- sh -c '. ~/.profile; /judge/env/bin/dmoj-autoconf -V'
